### ISSUE TITLE
accomodate longer email addresses

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-payment-methods#3]
maybe we should truncate emails that are too long?

![pasted image at 2017_10_09 03_56 pm](https://user-images.githubusercontent.com/313947/31356172-4948e228-acfa-11e7-8302-38dd3b8dc444.png)

**Comment by Tolmark12** [comment]
Fixed / pushed, ready for deploy.

**Comment by jedgalbraith** [comment]
This still looks the same. I've updated this component to #87100c3db2. Is there anything else I need to update?

![screen shot 2017-10-30 at 11 31 24 am](https://user-images.githubusercontent.com/313947/32185823-ef444c46-bd65-11e7-82f8-85b4d7c5ff00.png)

**Comment by jedgalbraith** [comment]
Just had to update core-styles. Fixed now.
